<<<<<<< HEAD
page:
    resource: "@PageBundle/Resources/config/routing.yml"
    prefix:   /

ecommerce:
    resource: "@EcommerceBundle/Resources/config/routing.yml"
    prefix:   /

## route principal : http://localhost/.git/e-commerce/web/app_dev.php/panier
=======
>>>>>>> f7662a2da6d9544f5d30c387839405c60af09cf9
